import { useEffect, useState } from 'react';
import { callApi, type BattleDeckConfig, type CardMaster } from './api';

interface AdminData {
  settings: { key: string; value: string; description: string }[];
  cards: CardMaster[];
  packs: { packId: string; name: string; price: number; cardsPerPack: number; rarityRates: Record<string, number>; cardPool: string[]; pityCount: number; active: boolean }[];
  missions: { missionId: string; period: string; condition: string; targetCount: number; reward: number; label: string; active: boolean }[];
  decks: BattleDeckConfig[];
}

type Pack = AdminData['packs'][number];
const missionConditions = [['win_battle','対戦で勝つ'],['play_cpu','CPUと対戦'],['train','トレーニング'],['open_pack','パックを開ける'],['login','ログイン'],['submit_test','テストを受ける'],['perfect_test','テスト満点'],['submit_reflection','振り返りを提出'],['play_online','オンラインで対戦']];
function PackEditor({ pack, cards, busy, onChange, onSave }: { pack: Pack; cards: CardMaster[]; busy: boolean; onChange: (value: Pack) => void; onSave: () => void }) {
  const rateTotal = Object.values(pack.rarityRates).reduce((sum, rate) => sum + Number(rate), 0);
  return <div className="admin-pack"><h3>{pack.name}</h3><div className="admin-economy-grid">
    <label>価格<input type="number" min="0" value={pack.price} onChange={(event) => onChange({ ...pack, price: Number(event.target.value) })} /></label>
    <label>1パックの枚数<input type="number" min="1" max="10" value={pack.cardsPerPack} onChange={(event) => onChange({ ...pack, cardsPerPack: Number(event.target.value) })} /></label>
    <label>天井までのパック数（0ならなし）<input type="number" min="0" value={pack.pityCount} onChange={(event) => onChange({ ...pack, pityCount: Number(event.target.value) })} /></label>
  </div><h4>排出率（合計100%）</h4><div className="admin-economy-grid">{(['N', 'R', 'SR', 'UR'] as const).map((rarity) => <label key={rarity}>{rarity} の排出率 %<input type="number" min="0" max="100" step="0.1" value={pack.rarityRates[rarity] ?? 0} onChange={(event) => onChange({ ...pack, rarityRates: { ...pack.rarityRates, [rarity]: Number(event.target.value) } })} /></label>)}</div><p>現在の合計：{rateTotal}%</p>
    <h4>収録カード</h4><div className="admin-economy-grid">{cards.filter((card) => card.active && card.inPack).map((card) => <label key={card.cardId}><input type="checkbox" checked={pack.cardPool.includes(card.cardId)} onChange={(event) => onChange({ ...pack, cardPool: event.target.checked ? [...pack.cardPool, card.cardId] : pack.cardPool.filter((id) => id !== card.cardId) })} />{card.name}（{card.rarity}）</label>)}</div>
    <label><input type="checkbox" checked={pack.active} onChange={(event) => onChange({ ...pack, active: event.target.checked })} />販売中</label>
    <button type="button" className="button button--ghost" disabled={busy || Math.abs(rateTotal - 100) > .001} onClick={onSave}>保存</button>
  </div>;
}

export function AdminEconomy({ session }: { session: string }) {
  const [data, setData] = useState<AdminData | null>(null);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [newMission, setNewMission] = useState<AdminData['missions'][number]>({ missionId: '', period: 'daily', condition: 'train', targetCount: 1, reward: 10, label: '', active: true });
  const [newPack, setNewPack] = useState<Pack>({ packId: '', name: '', price: 200, cardsPerPack: 3, rarityRates: { N: 70, R: 30 }, cardPool: [], pityCount: 0, active: false });
  useEffect(() => { let active = true; callApi<AdminData>('adminGetEconomy', session).then((result) => { if (active) setData(result); }).catch((error: Error) => { if (active) setMessage(error.message); }); return () => { active = false; }; }, [session]);
  const save = async (action: string, payload: object) => {
    setBusy(true); setMessage('');
    try { await callApi(action, session, payload); setData(await callApi<AdminData>('adminGetEconomy', session)); setMessage('保存しました。'); }
    catch (error) { setMessage((error as Error).message); }
    finally { setBusy(false); }
  };
  if (!data) return <section className="admin-economy panel"><h2>カードとゲームの設定</h2><p role="status">{message || '読み込み中…'}</p></section>;
  return <section className="admin-economy panel"><h2>カードとゲームの設定</h2><p>仮の価格や報酬をここで変更できます。変更後の操作から反映されます。</p>
    <details><summary>Gポイントと育成の数値</summary><div className="admin-economy-grid">{data.settings.map((setting, index) => <div className="admin-setting" key={setting.key}><label>{setting.description}<input type="number" min={setting.key === 'lifePerRun' ? '1' : '0'} max="100000" value={setting.value} onChange={(event) => setData((current) => { if (!current) return current; const settings = [...current.settings]; settings[index] = { ...settings[index], value: event.target.value }; return { ...current, settings }; })} /></label><button type="button" className="button button--ghost" disabled={busy || (setting.key === 'lifePerRun' && Number(setting.value) < 1)} onClick={() => { void save('adminSaveSettings', { key: setting.key, value: setting.value }); }}>保存</button></div>)}</div></details>
    <details><summary>カードの販売設定</summary><div className="admin-economy-grid">{data.cards.map((card, index) => <div className="admin-setting" key={card.cardId}><strong>{card.name}（{card.rarity}）</strong><label>単品価格（空欄なら販売しない）<input type="number" min="0" max="100000" value={card.shopPrice ?? ''} onChange={(event) => setData((current) => { if (!current) return current; const cards = [...current.cards]; cards[index] = { ...cards[index], shopPrice: event.target.value === '' ? null : Number(event.target.value) }; return { ...current, cards }; })} /></label><label><input type="checkbox" checked={card.inPack} onChange={(event) => setData((current) => { if (!current) return current; const cards = [...current.cards]; cards[index] = { ...cards[index], inPack: event.target.checked }; return { ...current, cards }; })} />パックに入れる</label><label><input type="checkbox" checked={card.active} onChange={(event) => setData((current) => { if (!current) return current; const cards = [...current.cards]; cards[index] = { ...cards[index], active: event.target.checked }; return { ...current, cards }; })} />購入できる状態</label><button type="button" className="button button--ghost" disabled={busy} onClick={() => { void save('adminSaveCard', { cardId: card.cardId, shopPrice: card.shopPrice, inPack: card.inPack, active: card.active }); }}>保存</button></div>)}</div></details>
    <details><summary>パックの設定</summary>{data.packs.map((pack, index) => <PackEditor key={pack.packId} pack={pack} cards={data.cards} busy={busy} onChange={(value) => setData((current) => { if (!current) return current; const packs = [...current.packs]; packs[index] = value; return { ...current, packs }; })} onSave={() => { const rarityRates = Object.fromEntries(Object.entries(pack.rarityRates).filter(([, rate]) => rate > 0)); void save('adminSavePack', { ...pack, rarityRates }); }} />)}</details>
    <details><summary>新しいパックを追加</summary><div className="admin-economy-grid"><label>パックID（英小文字・数字・ハイフン）<input value={newPack.packId} onChange={(event) => setNewPack({ ...newPack, packId: event.target.value })} /></label><label>パック名<input value={newPack.name} onChange={(event) => setNewPack({ ...newPack, name: event.target.value })} /></label></div><PackEditor pack={newPack} cards={data.cards} busy={busy} onChange={setNewPack} onSave={() => { const rarityRates = Object.fromEntries(Object.entries(newPack.rarityRates).filter(([, rate]) => rate > 0)); void save('adminSavePack', { ...newPack, rarityRates }); }} /></details>
    <details><summary>ミッションの設定</summary><div className="admin-economy-grid">{data.missions.map((mission, index) => <div className="admin-setting" key={mission.missionId}><strong>{mission.missionId}</strong><label>表示名<input value={mission.label} onChange={(event) => setData((current) => { if (!current) return current; const missions = [...current.missions]; missions[index] = { ...missions[index], label: event.target.value }; return { ...current, missions }; })} /></label><label>期間<select value={mission.period} onChange={(event) => setData((current) => { if (!current) return current; const missions = [...current.missions]; missions[index] = { ...missions[index], period: event.target.value }; return { ...current, missions }; })}><option value="daily">毎日</option><option value="weekly">毎週</option></select></label><label>条件<select value={mission.condition} onChange={(event) => setData((current) => { if (!current) return current; const missions = [...current.missions]; missions[index] = { ...missions[index], condition: event.target.value }; return { ...current, missions }; })}>{missionConditions.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>必要回数<input type="number" min="1" value={mission.targetCount} onChange={(event) => setData((current) => { if (!current) return current; const missions = [...current.missions]; missions[index] = { ...missions[index], targetCount: Number(event.target.value) }; return { ...current, missions }; })} /></label><label>報酬<input type="number" min="0" value={mission.reward} onChange={(event) => setData((current) => { if (!current) return current; const missions = [...current.missions]; missions[index] = { ...missions[index], reward: Number(event.target.value) }; return { ...current, missions }; })} /></label><label><input type="checkbox" checked={mission.active} onChange={(event) => setData((current) => { if (!current) return current; const missions = [...current.missions]; missions[index] = { ...missions[index], active: event.target.checked }; return { ...current, missions }; })} />有効</label><button type="button" className="button button--ghost" disabled={busy} onClick={() => { void save('adminSaveMission', mission); }}>保存</button></div>)}</div></details>
    <details><summary>新しいミッションを追加</summary><div className="admin-economy-grid"><label>ID（英小文字・数字・ハイフン）<input value={newMission.missionId} onChange={(event) => setNewMission({ ...newMission, missionId: event.target.value })} /></label><label>表示名<input value={newMission.label} onChange={(event) => setNewMission({ ...newMission, label: event.target.value })} /></label><label>期間<select value={newMission.period} onChange={(event) => setNewMission({ ...newMission, period: event.target.value })}><option value="daily">毎日</option><option value="weekly">毎週</option></select></label><label>条件<select value={newMission.condition} onChange={(event) => setNewMission({ ...newMission, condition: event.target.value })}>{missionConditions.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>必要回数<input type="number" min="1" value={newMission.targetCount} onChange={(event) => setNewMission({ ...newMission, targetCount: Number(event.target.value) })} /></label><label>報酬<input type="number" min="0" value={newMission.reward} onChange={(event) => setNewMission({ ...newMission, reward: Number(event.target.value) })} /></label></div><button type="button" className="button button--ghost" disabled={busy || !newMission.missionId || !newMission.label} onClick={() => { void save('adminSaveMission', newMission); }}>追加する</button></details>
    <details><summary>サンプル・CPUデッキの設定</summary><div className="admin-economy-grid">{data.decks.map((deck, index) => <div className="admin-setting" key={deck.deckId}><strong>{deck.name}</strong><p>候補カードを4枚以上選んでください。</p>{data.cards.filter((card) => card.active).map((card) => <label key={card.cardId}><input type="checkbox" checked={deck.cardIds.includes(card.cardId)} onChange={(event) => setData((current) => { if (!current) return current; const decks = [...current.decks]; decks[index] = { ...decks[index], cardIds: event.target.checked ? [...decks[index].cardIds, card.cardId] : decks[index].cardIds.filter((id) => id !== card.cardId) }; return { ...current, decks }; })} />{card.name}</label>)}<label>最大ライフ<input type="number" min="1" value={deck.maxLife} onChange={(event) => setData((current) => { if (!current) return current; const decks = [...current.decks]; decks[index] = { ...decks[index], maxLife: Number(event.target.value) }; return { ...current, decks }; })} /></label><label>CPUの筋トレ値<input type="number" min="0" value={deck.rockTrainLevel} onChange={(event) => setData((current) => { if (!current) return current; const decks = [...current.decks]; decks[index] = { ...decks[index], rockTrainLevel: Number(event.target.value) }; return { ...current, decks }; })} /></label><button type="button" className="button button--ghost" disabled={busy || deck.cardIds.length < 4} onClick={() => { void save('adminSaveDeck', deck); }}>保存</button></div>)}</div></details>
    {message && <p role="status" className="economy-message">{message}</p>}
  </section>;
}
